from __future__ import annotations

import warnings
import numpy as np
import pandas as pd
import nptyping as npt
import xarray as xr
from nptyping import NDArray, Int8, Int64, Float64, Bool, Shape, Float, Int
from typing import Any, Hashable, List, Iterable, Callable, Union, Dict
from functools import cached_property

import xftsim as xft


def founder_haplotypes_from_AFs(n: int,
                                afs: Iterable,
                                diploid: bool = True,
                                generation: int = 0) -> xft.struct.NHaplotypeArray:
    """
    Generate founder haplotypes from specified allele frequencies.

    Parameters
    ----------
    n : int
        Number of individuals to simulate.
    afs : Iterable
        Allele frequencies as an iterable of floats (one per variant).
    diploid : bool, optional
        Flag indicating if the generated haplotypes should be diploid or haploid.
    generation : int, optional
        Generation number for the founders. Default is 0.

    Returns
    -------
    xft.struct.NHaplotypeArray
        An object representing a set of haplotypes generated from the given allele frequencies.
    """
    afs = np.asarray(afs).ravel()
    m = len(afs)

    # Generate 3D genotypes array (n, m, 2) using fully vectorized sampling.
    # Each haplotype copy is sampled independently from Bernoulli(af).
    # Broadcasting af over the sample dimension avoids a Python-level loop.
    af_row = afs[np.newaxis, :]  # shape (1, m)
    genotypes = np.empty((n, m, 2), dtype=np.int8)
    genotypes[:, :, 0] = (np.random.random((n, m)) < af_row).astype(np.int8)
    genotypes[:, :, 1] = (np.random.random((n, m)) < af_row).astype(np.int8)

    # Create sample metadata
    iid = np.arange(n, dtype=np.int64)
    samples = xft.struct.SampleMeta(iid=iid)

    # Create variant metadata with allele frequencies
    vid = np.arange(m, dtype=np.int64)
    variants = xft.struct.VariantMeta(vid=vid, af=afs)

    return xft.struct.NHaplotypeArray(
        genotypes=genotypes,
        generation=generation,
        samples=samples,
        variants=variants,
    )


def founder_haplotypes_uniform_AFs(n: int,
                                   m: int,
                                   minMAF: float = .1,
                                   generation: int = 0) -> xft.struct.NHaplotypeArray:
    """
    Generate founder haplotypes from uniform-distributed allele frequencies.

    Parameters
    ----------
    n : int
        Number of individuals to simulate.
    m : int
        Number of variants.
    minMAF : float, optional
        Minimum minor allele frequency for generated haplotypes.
    generation : int, optional
        Generation number for the founders. Default is 0.

    Returns
    -------
    xft.struct.NHaplotypeArray
        An object representing a set of haplotypes generated with uniform allele frequencies.
    """
    afs = np.random.uniform(minMAF, 1 - minMAF, m)
    return founder_haplotypes_from_AFs(n=n,
                                       afs=afs,
                                       diploid=True,
                                       generation=generation)


def founder_haplotypes_from_sgkit_dataset(gdat: xr.Dataset,
                                          generation: int = 0) -> xft.struct.NHaplotypeArray:
    """Construct founder haplotypes array from sgkit DataArray.
    Useful in conjuction with sgkit.io.vcf.vcf_to_zarr() and sgkit.load_dataset()

    Parameters
    ----------
    gdat : xr.Dataset
        Dataset generated by sgkit.load_dataset()
    generation : int, optional
        Generation number for the founders. Default is 0.

    Returns
    -------
    xft.struct.NHaplotypeArray
        Array of founder haplotypes.
    """
    return xft.io.haplotypes_from_sgkit_dataset(gdat, generation=generation)


def founder_haplotypes_from_plink_bfile(path: str,
                                        generation: int = 0) -> xft.struct.NHaplotypeArray:
    """
    Reads in PLINK 1 binary genotype data and returns a NHaplotypeArray object containing pseudo-haplotypes by
    randomly assigning haplotypes at heterozygous sites.

    Parameters
    ----------
    path : str
        The file path to the PLINK 1 binary genotype data.
    generation : int, optional
        Generation number for the founders. Default is 0.

    Returns
    -------
    xft.struct.NHaplotypeArray
        Founder Pseudo-haplotype array. The "pseudo-" prefix refers to the fact that the
        plink bfile format doesn't track phase.
    """
    return xft.io.read_plink1_as_pseudohaplotypes(path, generation=generation)
