import warnings
import numpy as np
import numba as nb
import pandas as pd
import dask.array as da
import nptyping as npt
import xarray as xr
from nptyping import NDArray, Int8, Int64, Float64, Bool, Shape, Float, Int
from typing import Any, Hashable, List, Iterable, Callable, Union, Dict
from functools import cached_property
import pandas_plink as pp
from dask.diagnostics import ProgressBar

import xftsim as xft


@nb.njit
def _genotypes_to_pseudo_haplotypes_3d(genotypes):
    """
    Converts genotype data to pseudo-haplotype 3D array.

    Parameters
    ----------
    genotypes : ndarray
        2D array of genotype data (n, m) with values 0, 1, 2.

    Returns
    -------
    ndarray
        3D array of pseudo-haplotype data (n, m, 2).
    """
    n, m = genotypes.shape
    haplotypes = np.zeros((n, m, 2), dtype=np.int8)
    for i in range(n):
        for j in range(m):
            g = genotypes[i, j]
            if g == 0:
                haplotypes[i, j, 0] = 0
                haplotypes[i, j, 1] = 0
            elif g == 1:
                # Randomly assign which haplotype gets the 1
                if np.random.random() < 0.5:
                    haplotypes[i, j, 0] = 1
                    haplotypes[i, j, 1] = 0
                else:
                    haplotypes[i, j, 0] = 0
                    haplotypes[i, j, 1] = 1
            elif g == 2:
                haplotypes[i, j, 0] = 1
                haplotypes[i, j, 1] = 1
    return haplotypes


def genotypes_to_pseudo_haplotypes(genotypes: np.ndarray) -> np.ndarray:
    """
    Converts genotype data to pseudo-haplotype 3D array.

    Parameters
    ----------
    genotypes : np.ndarray
        2D array of genotype data (n, m) with values 0, 1, 2.

    Returns
    -------
    np.ndarray
        3D array of pseudo-haplotype data (n, m, 2).
    """
    return _genotypes_to_pseudo_haplotypes_3d(genotypes.astype(np.int8))


def read_plink1_as_pseudohaplotypes(path: str,
                                    generation: int = 0) -> xft.struct.NHaplotypeArray:
    """
    Reads in PLINK 1 binary genotype data and returns a NHaplotypeArray object containing pseudo-haplotypes by
    randomly assigning haplotypes at heterozygous sites.

    Parameters
    ----------
    path : str
        The file path to the PLINK 1 binary genotype data.
    generation : int, optional
        Generation number. Default is 0.

    Returns
    -------
    xft.struct.NHaplotypeArray
        Pseudo-haplotype array. The "pseudo-" prefix refers to the fact that the
        plink bfile format doesn't track phase.

    Raises
    ------
    ValueError
        If the specified file path does not exist or is not in the expected format.
    """
    # Read genotype data
    bim, fam, bed = pp.read_plink(path)

    # bed is (m, n) in dask, transpose to (n, m)
    with ProgressBar():
        genotypes = bed.T.compute().astype(np.int8)

    n, m = genotypes.shape

    # Convert to 3D pseudo-haplotypes
    haplotypes_3d = genotypes_to_pseudo_haplotypes(genotypes)

    # Create variant IDs
    if np.all(bim.snp.values == '.'):
        vid = np.char.add(
            np.char.add(bim.chrom.values.astype(str), ':'),
            bim.pos.values.astype(str)
        )
    else:
        vid = bim.snp.values

    # Create variant metadata
    chrom = bim.chrom.values
    pos_bp = bim.pos.values
    pos_cM = bim.cm.values if not np.all(bim.cm.values == 0) else None
    zero_allele = bim.a0.values
    one_allele = bim.a1.values

    variants = xft.struct.VariantMeta(
        vid=vid,
        chrom=chrom,
        pos_bp=pos_bp,
        pos_cM=pos_cM,
        zero_allele=zero_allele,
        one_allele=one_allele,
    )

    # Create sample metadata
    iid = fam.iid.values.astype(str)
    fid = fam.fid.values.astype(str)
    # pandas_plink: gender 1=male, 2=female, 0=unknown
    # xftsim: sex 0=female, 1=male
    sex = (2 - fam.gender.values).astype(int)
    sex[fam.gender.values == 0] = 0  # unknown -> default to female

    samples = xft.struct.SampleMeta(iid=iid, fid=fid, sex=sex)

    return xft.struct.NHaplotypeArray(
        genotypes=haplotypes_3d,
        generation=generation,
        samples=samples,
        variants=variants,
    )


def haplotypes_from_sgkit_dataset(gdat: xr.Dataset,
                                  generation: int = 0) -> xft.struct.NHaplotypeArray:
    """Construct haplotype array from sgkit DataArray.
    Useful in conjuction with sgkit.io.vcf.vcf_to_zarr() and sgkit.load_dataset()

    Parameters
    ----------
    gdat : xr.Dataset
        Dataset generated by sgkit.load_dataset()
    generation : int, optional
        Generation number. Default is 0.

    Returns
    -------
    xft.struct.NHaplotypeArray
        Haplotype array.
    """
    # Genotypes are already in 3D format (samples, variants, ploidy)
    # sgkit uses (variants, samples, ploidy), so we need to transpose
    genotypes = gdat.call_genotype.values.transpose(1, 0, 2).astype(np.int8)

    # Create sample metadata
    iid = gdat.sample_id.values.astype(str)
    samples = xft.struct.SampleMeta(iid=iid)

    # Create variant metadata
    chrom = np.array(gdat.contigs)[gdat.variant_contig.values]
    pos_bp = gdat.variant_position.values
    vid = np.char.add(
        np.char.add(chrom.astype(str), ':'),
        pos_bp.astype(str)
    )

    # Get alleles if available
    alleles = gdat.variant_allele.values if 'variant_allele' in gdat else None
    zero_allele = alleles[:, 0].astype(str) if alleles is not None else None
    one_allele = alleles[:, 1].astype(str) if alleles is not None else None

    variants = xft.struct.VariantMeta(
        vid=vid,
        chrom=chrom,
        pos_bp=pos_bp,
        zero_allele=zero_allele,
        one_allele=one_allele,
    )

    return xft.struct.NHaplotypeArray(
        genotypes=genotypes,
        generation=generation,
        samples=samples,
        variants=variants,
    )


def save_haplotypes_npz(haplotypes: xft.struct.NHaplotypeArray,
                        path: str) -> None:
    """
    Save NHaplotypeArray to compressed numpy format.

    Parameters
    ----------
    haplotypes : xft.struct.NHaplotypeArray
        The haplotype data to save.
    path : str
        The path to save to (will add .npz extension if not present).
    """
    save_dict = {
        'genotypes': haplotypes.genotypes,
        'generation': np.array([haplotypes.generation]),
        # Sample metadata
        'sample_iid': haplotypes.samples.iid,
        'sample_fid': haplotypes.samples.fid,
        'sample_sex': haplotypes.samples.sex,
        # Variant metadata
        'variant_vid': haplotypes.variants.vid,
    }

    # Add optional variant metadata if present
    if haplotypes.variants.chrom is not None:
        save_dict['variant_chrom'] = haplotypes.variants.chrom
    if haplotypes.variants.pos_bp is not None:
        save_dict['variant_pos_bp'] = haplotypes.variants.pos_bp
    if haplotypes.variants.pos_cM is not None:
        save_dict['variant_pos_cM'] = haplotypes.variants.pos_cM
    if haplotypes.variants.af is not None:
        save_dict['variant_af'] = haplotypes.variants.af
    if haplotypes.variants.zero_allele is not None:
        save_dict['variant_zero_allele'] = haplotypes.variants.zero_allele
    if haplotypes.variants.one_allele is not None:
        save_dict['variant_one_allele'] = haplotypes.variants.one_allele

    np.savez_compressed(path, **save_dict)


def load_haplotypes_npz(path: str) -> xft.struct.NHaplotypeArray:
    """
    Load NHaplotypeArray from compressed numpy format.

    Parameters
    ----------
    path : str
        The path to load from.

    Returns
    -------
    xft.struct.NHaplotypeArray
        The loaded haplotype array.
    """
    data = np.load(path, allow_pickle=True)

    # Load sample metadata
    samples = xft.struct.SampleMeta(
        iid=data['sample_iid'],
        fid=data['sample_fid'],
        sex=data['sample_sex'],
    )

    # Load variant metadata
    variants = xft.struct.VariantMeta(
        vid=data['variant_vid'],
        chrom=data['variant_chrom'] if 'variant_chrom' in data else None,
        pos_bp=data['variant_pos_bp'] if 'variant_pos_bp' in data else None,
        pos_cM=data['variant_pos_cM'] if 'variant_pos_cM' in data else None,
        af=data['variant_af'] if 'variant_af' in data else None,
        zero_allele=data['variant_zero_allele'] if 'variant_zero_allele' in data else None,
        one_allele=data['variant_one_allele'] if 'variant_one_allele' in data else None,
    )

    return xft.struct.DenseHaplotypeArray(
        genotypes=data['genotypes'],
        generation=int(data['generation'][0]),
        samples=samples,
        variants=variants,
    )


# Legacy functions for XarrayHaplotypeArray compatibility

def plink1_variant_index(ppxr: xr.DataArray) -> xft.index.DiploidVariantIndex:
    """
    Create a DiploidVariantIndex object from a plink file DataArray generated by pandas_plink.

    Parameters
    ----------
    ppxr : xr.DataArray
        An xarray DataArray representing a plink file.

    Returns
    -------
    xft.index.DiploidVariantIndex
        A DiploidVariantIndex object.
    """
    if np.all(ppxr.snp.values == '.'):
        vid = np.char.add(np.char.add(ppxr.chrom.values.astype(str), ':'), ppxr.pos.values.astype(str))
    else:
        vid = ppxr.snp.values
    if np.all(ppxr.cm.values == 0):
        cm = np.full(ppxr.cm.shape, fill_value=np.NaN)
    else:
        cm = ppxr.cm
    return xft.index.DiploidVariantIndex(
        vid=vid,
        chrom=ppxr.chrom.values,
        zero_allele=ppxr.a0.values,
        one_allele=ppxr.a1.values,
        pos_bp=ppxr.pos,
        pos_cM=cm,
    )


def plink1_sample_index(ppxr: xr.DataArray,
                        generation: int = 0) -> xft.index.SampleIndex:
    """
    Create a SampleIndex object from a plink file DataArray generated by pandas_plink.

    Parameters
    ----------
    ppxr : xr.DataArray
        An xarray DataArray representing a plink file.
    generation : int, optional
        The generation of the individuals, by default 0.

    Returns
    -------
    xft.index.SampleIndex
        A SampleIndex object.
    """
    return xft.index.SampleIndex(
        iid=ppxr.iid.values.astype(str),
        fid=ppxr.fid.values.astype(str),
        sex=2 - ppxr.gender.values.astype(int),
        generation=generation,
    )
